### ISSUE TITLE
Class to simplify communication with the pi

### ISSUE THREAD

**Issue by Lionel1232** [IRTSA-SoftwareProject/IRTSA-App#3]
## Description:
A class to simplify communication with the Raspberry pi using the JSCH library will have to be developed.

## Justification:
- This will help separate concerns of the application
- Standardize the way the app communicates with the pi

**Comment by jamesfer** [comment]
I was basically imagining some sort of interface where you could call a method called `runRemoteCommand` (or something to the same effect) and give it the script name to run, as well as any arguments. It would handle the connection, logging in, running the script and the return some kind of out put from the script.

The return value would need to be something that is filled in asynchronously, so we can update the UI on progress events. For this I was considering something such as Observables (https://github.com/ReactiveX/RxJava) which let you create a stream of events and each even could be a message from the server (or something similar if you've had experience with anything else).

If the interface class could also parse the output of the server script into a more sensible format, it might make it easier as well. Eg. all python scripts could return their output in something like this:

    progress: "10% complete"
    progress: "20% complete"
    ....
    complete: { "filename": "scan 1.jpg", "startedAt": 1002357437884, "finishedAt": 1002357547884 }

Where the part before the colon is the message type, and the part afterwards is a JSON string of the response data (or, again, something to the same effect). This way each script could send back specific messages about it's status and it would be easier to interpret them on the app as new messages could be added without interfering with the existing ones because they each have a different message type.

They are just some of the things I had considered implementing.

**Comment by Lionel1232** [comment]
Hey thanks heaps for that detailed info.
I'm familiar with the observer pattern but haven't heard of RxJava so will check that out now and get a little more familiar with it.
I think it's definitely a good idea to have some standard format to send messages back/forth from the server to the phone and vice versa, will definitely make things a little easier.
